application: monkey-port
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:

# ndb_users
- url: /_login/assets
  static_dir: ndb_users/assets
- url: /_login(.*)
  script: ndb_users.login.app
  secure: always
- url: /_ah/bounce
  script: ndb_users.mail.app
  login: admin

- url: /api/.*
  script: api.APP
  secure: always

- url: /call/.*
  script: call.APP
  secure: always

- url: /messages/.*
  script: messages.APP
  secure: always

# Static files
- url: /(.*\.(gif|png|jpg|css|js|html|woff2|svg|eot|woff|ttf))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|css|js|html|woff2|svg|eot|woff|ttf)$

# AngularJS app stub
- url: /.*
  static_files: static/app.html
  upload: static/app.html
  secure: always


libraries:
- name: webapp2
  version: latest